config/routes.rb
Rails.application.routes.draw do
  resources :my_meals
  resources :meals
  resources :meal_times

 # get 'nutritionist/index'
  get 'nutritionist' => 'nutritionist#index'

  resources :restaurants
  resources :types
  resources :foods

  resources :searches

# the routes for the log in and log out 
  get 'admin' => 'admin#index' 
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end


  resources :users

# the route to our home page 
  root to: 'visitors#index'

# the route to the shape that will show the result after searching for a food by neame 
  get 'fsearch' => 'foods#fsearch'

# the routes for the steps of configuring a meal 
  get 'configure_a_meal' => 'meal_times#step1'
  get 'configure_a_meal_step1' => 'restaurants#step2'
  get 'configure_a_meal_step2' => 'types#step3'
  get 'configure_a_meal_step3' => 'foods#step4'



end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]
  #do not check if the user is logged in before preforming step3
  skip_before_action :authenticate, only: [:step3]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def step3
    @types = Type.clickedrestaurant(params[:restaurant])
    $restaurant = params[:restaurant]

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<!-- the form to add and edit type -->

<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-left">
    <%= f.label :name, class: 'form-group' %><br>
    <%= f.text_field :name, class: 'appformcontrol form-control' %>
  </div>
  
  <div class="actions">
    <%= f.submit class: ' appformbutton btn btn-info' %>
    <%= link_to 'Back', types_path, class: 'appformbutton btn btn-info appbackbutton'%>
  </div>
<% end %>

app/views/types/edit.html.erb
<!-- the edit page -->

<!--Start Edit types Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div class="section-title text-center">
          <h3>Edit Type</h3>
        </div>
      </div>
<!--end Edit type Heading section-->
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <section>
            <div class="shadbox">
              <div class="panel-body">
                <!-- the form is rendered in this page -->
                <%= render 'form' %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>
               
                              

app/views/types/index.html.erb
<!-- the page that lists all the types in the application -->

<!-- Start types Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="appHeading" class="section-title text-center">
          <h3>Listing types</h3>
          <p>Add, Edit and Delete types</p>
        </div>
      </div>
<!--end of types heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div id="listingappPanel">
            <div class="panel-body shadbox">
              <table class="table text-left" >
                <tr>
                  <th>type Name</th>
                </tr>
                <% @types.each do |type| %>
                  <tr>
                                            
                  <td><%= type.name %></td>
                  <td> 
                    <div class="pull-right hidden-phone">
                      <div id="listingappbuttons">
                        <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-check"></i>-->
                          <%= link_to '', type, :class =>'fa fa-check' %>
                        </button>
                        <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-pencil"></i>-->
                          <%= link_to '', edit_type_path(type), :class =>'fa fa-pencil' %>
                        </button>
                        <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-times"></i>-->
                          <%= link_to '', type, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'fa fa-times' %>
                        </button>
                      </div>
                    </div>
                  </td>
                  </tr>
                <% end %>
              </table>
              <%= link_to 'Add New type', new_type_path, class: 'appformbutton btn btn-info appbackbutton'%>
              <%= link_to 'Back', nutritionist_path, class: 'appformbutton btn btn-info appbackbutton'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/types/new.html.erb
<!-- create new type page -->
         <!--Start newtype Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div class="section-title text-center">
          <h3>New Type</h3>
        </div>
      </div>
            <!--end new type heading section -->
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <section>
            <div class="shadbox">
              <div class="panel-body">
                <%= render 'form' %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

               

app/views/types/show.html.erb
<!-- This page shows the specific type page -->
<!-- Start Showtypes Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="ShowappsHeading" class="section-title text-center">
          <h3>Show type</h3>
        </div>
      </div>
<!--end of showtypes heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div id="showappPanel" >
            <div class="panel-body shadbox">
              <table class="table text-left">
                <tr>
                  <th>type</th>
                </tr>
                <tr>
                  <td><%= @type.name %></td>
                  <td>
                    <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-pencil"></i>-->
                          <%= link_to '', edit_type_path, :class =>'fa fa-pencil' %>
                      </button>
                    </td>
                </tr>
              </table>
              <div class="row">
              <%= link_to 'Back', types_path, class: 'appformbutton btn btn-info appbackbutton'%>
            </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
             

app/views/types/step3.html.erb
<!--  this is step 3 in configure a meal, if showes all the types that are available in specific time and at specific restaurant -->


<!-- Start users Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="appHeading" class="section-title text-center">
          <h3>Step 3</h3>
          <p>Choose your desired food group</p>
        </div>
      </div>
<!--end of users heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          
            <div class=" shadbox">
              <div class="step3font">
              <table class="table text-center" >
                <% if @types.empty? %>
                <p> No records found</p>
                <% else %>

                <% @types.each do |type| %>
                  <tr>
                  <td>
                    <%= link_to type.name, configure_a_meal_step3_path(:type => type.name) %>
                  </td>
                  </tr>
 <% end %>
                  <% end %>
                </table>
                </div>

            </div>
        </div>
      </div>
    </div>
  </div>
</div>