config/routes.rb
Rails.application.routes.draw do
  resources :my_meals
  resources :meals
  resources :meal_times

 # get 'nutritionist/index'
  get 'nutritionist' => 'nutritionist#index'

  resources :restaurants
  resources :types
  resources :foods

  resources :searches

# the routes for the log in and log out 
  get 'admin' => 'admin#index' 
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end


  resources :users

# the route to our home page 
  root to: 'visitors#index'

# the route to the shape that will show the result after searching for a food by neame 
  get 'fsearch' => 'foods#fsearch'

# the routes for the steps of configuring a meal 
  get 'configure_a_meal' => 'meal_times#step1'
  get 'configure_a_meal_step1' => 'restaurants#step2'
  get 'configure_a_meal_step2' => 'types#step3'
  get 'configure_a_meal_step3' => 'foods#step4'



end

app/models/user.rb
class User < ActiveRecord::Base


  #Adds methods to set and authenticate against a BCrypt password.
  has_secure_password

  # before saving the name, change it to downcase
  before_save { self.name = name.downcase }

  #Validations 
	validates :name, presence: true, uniqueness: true
	validates :password, length: { minimum: 8 }
 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  #before preforming any task check if the user is admin
  before_action :admin_only

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User #{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #params.require(:user).permit(:name, :password, :password_confirmation, :admin)
      params.require(:user).permit(:name, :password, :password_confirmation, :admin)
    end


# a method that check if the user is admin or not
   def admin_only
      if !current_user.admin?
        redirect_to root_path
      end 
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- the form to add and edit users -->
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-left">
    <%= f.label :name, class: 'form-group' %><br>
    <%= f.text_field :name, class: 'appformcontrol form-control' %>
  </div>
  <div class="field text-left">
    <%= f.label :password,  class: 'form-group' %><br>
    <%= f.password_field :password, class: 'appformcontrol form-control' %>
  </div>
  <div class="field text-left">
    <%= f.label :password_confirmation, class: 'form-group'  %><br>
    <%= f.password_field :password_confirmation, class: 'appformcontrol form-control' %>
  </div>
  <div class="field text-left">

    <%= f.check_box :admin %>Admin 
 &nbsp; &nbsp;<%= f.label :admin, class: 'admincheck form-group' do %>
  <% end %>
    
    </div>
    <div class="actions">
      <%= f.submit class: 'userformbutton btn btn-info' %>
      <%= link_to 'Back', users_path, class: 'userformbutton btn btn-info userbackbutton'%>
    </div>

<% end %>

app/views/users/edit.html.erb
<!-- the edit page -->




<!--Start Edit user Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div class="section-title text-center">
          <h3>Edit User</h3>
        </div>
      </div>
<!--end Edit user Heading section-->
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <section>
            <div class="shadbox">
              <div class="panel-body">
                <!-- the form is rendered in this page -->
                <%= render 'form' %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>
               
                              

app/views/users/index.html.erb
<!-- the page that lists all the users in the application -->


<!-- Start users Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="appHeading" class="section-title text-center">
          <h3>Listing users</h3>
          <p>Add, Edit and Delete users</p>
        </div>
      </div>
<!--end of users heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div id="listingappPanel" >
            <div class="panel-body shadbox">
              <table class="table text-left" >
                <tr>
                  <th>User</th>
                  <th>Admin</th>
                  <th></th>
                </tr>
                <% @users.each do |user| %>
                  <tr>
                  <td><%= user.name %></td>
                  <td><%= user.admin %></td>
                  <td> 
                    <div class="pull-right hidden-phone">
                        <div id="listingappbuttons">
                          <button class="btn btn-default btn-xs">
                            <!--<i class="fa fa-check"></i>-->
                            <%= link_to '', user, :class =>'fa fa-check' %>
                          </button>
                          <button class="btn btn-default btn-xs">
                            <!--<i class="fa fa-pencil"></i>-->
                            <%= link_to '', edit_user_path(user), :class =>'fa fa-pencil' %>
                          </button>
                          <button class="btn btn-default btn-xs">
                            <!--<i class="fa fa-times"></i>-->
                            <%= link_to '', user, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'fa fa-times' %>
                          </button>
                        </div>
                      </div>
                    </td>
                    </tr>
                  <% end %>
                </table>
              <%= link_to 'Add New user', new_user_path, class: 'appformbutton btn btn-info appbackbutton'%>
              <%= link_to 'Back', admin_path, class: 'appformbutton btn btn-info appbackbutton'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<!-- create new user page -->
         <!--Start new user Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div class="section-title text-center">
          <h3>New User</h3>
        </div>
      </div>
            <!--end new user heading section            -->
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <section>
            <div class="shadbox">
              <div class="panel-body">
                <%= render 'form' %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- This page shows the specific user page -->


<!-- Start Showusers Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="ShowappsHeading" class="section-title text-center">
          <h3>Show user</h3>
        </div>
      </div>
<!--end of showusers heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div id="showappPanel" >
            <div class="panel-body shadbox">
              <table class="table text-left">
                <tr>
                    <th>Name</th>
                    <th>Admin</th>
                </tr>
                <tr>
                    <td><%= @user.name %></td>
                    <td><%= @user.admin %> </td>
                    <td>
                    <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-pencil"></i>-->
                          <%= link_to '', edit_user_path, :class =>'fa fa-pencil' %>
                      </button>
                    </td>
                </tr>
            </table>
              <div class="row">
              <%= link_to 'Back', users_path, class: 'appformbutton btn btn-info appbackbutton'%>
            </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
              