config/routes.rb
Rails.application.routes.draw do
  resources :my_meals
  resources :meals
  resources :meal_times

 # get 'nutritionist/index'
  get 'nutritionist' => 'nutritionist#index'

  resources :restaurants
  resources :types
  resources :foods

  resources :searches

# the routes for the log in and log out 
  get 'admin' => 'admin#index' 
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end


  resources :users

# the route to our home page 
  root to: 'visitors#index'

# the route to the shape that will show the result after searching for a food by neame 
  get 'fsearch' => 'foods#fsearch'

# the routes for the steps of configuring a meal 
  get 'configure_a_meal' => 'meal_times#step1'
  get 'configure_a_meal_step1' => 'restaurants#step2'
  get 'configure_a_meal_step2' => 'types#step3'
  get 'configure_a_meal_step3' => 'foods#step4'



end

app/models/food.rb
class Food < ActiveRecord::Base


	# before saving the name, change it to downcase
	before_save { self.name = name.downcase }

	#Relations
	belongs_to :type

	has_many :food_times
	has_many :meal_times, through: :food_times

	has_many :food_restaurants
	has_many :restaurants, through: :food_restaurants

	has_many :my_meal 
	
	#Validations
	validates :name, presence: true, uniqueness: true
	validates :type_id, presence: true

	#Nutirition fact info validations
	validates :servingSize, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :calories, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :protein, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :totalFat, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :saturated, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :trans, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :cholesterol, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :carbohydrates, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :sugars, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :dietaryFiber, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :sodium, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :potassium, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :magnesium, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :calcium, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :iron, presence: true, numericality: {greater_than_or_equal_to: 0}
	validates :vitaminD, presence: true, numericality: {greater_than_or_equal_to: 0}

	#Methods 
	#search through foods depending on the parameter passes either a name or keyward
	def self.search(search)
		if search
			where(["name LIKE ?","%#{search.downcase}%"])

		end
	end


	#A method used to move from step3 to step4 in configure a meal
	#It gets all the foodes depening on time, restaurant and types chosen
	def self.clickedtype(type)
		joins(:type).joins(:food_restaurants => :restaurant).joins(:food_times => :meal_time)
		.where(["foods.type_id = types.id
			and foods.id = food_restaurants.food_id 
			and food_restaurants.restaurant_id = restaurants.id 
			and foods.id = food_times.food_id 
			and food_times.meal_time_id = meal_times.id
			and meal_times.time LIKE ? 
			and restaurants.name LIKE ?
			and types.name LIKE ?", "%#{$time}%", "%#{$restaurant}%", "%#{type}%"]).distinct

	end


	
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  #do not check if the user is logged_in before preforming show, fsearch and step4 
  skip_before_action :authenticate, only: [:show, :fsearch, :step4]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }

        @food.restaurants = Restaurant.find(params[:restaurant_ids])
        @food.meal_times = MealTime.find(params[:meal_time_ids])
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # This method take us to a page the will present the results from search by name
  # The page will show all the records using method search from food model
  # :search is the keyword/name passed in the search page
  def fsearch
    @foods = Food.search(params[:search])
  end

  # This method take us to a page to be used for Step4 in Configure a Meal process
  # The page will show all the records useing method step4 from the model
  # :type is the clicked type 
  # $type stores the type as a global variable 
  def step4
    @foods = Food.clickedtype(params[:type])
    $type = params[:type]
  end 




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :type_id, :servingSize, :calories, :protein, :totalFat, :saturated, :trans, :cholesterol, :carbohydrates, :sugars, :dietaryFiber, :sodium, :potassium, :magnesium, :calcium, :iron, :vitaminD, :eggAllergy, :fishAllergy, :shellfishAllergy, :soyAllergy, :dairyAllergy, :milkAllergy, :wheatAllergy, :g6pdAllergy, :vegetarian)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<!-- the form to add and edit food -->

<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>
      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: 'form-group' %>
    <%= f.text_field :name, class: 'appformcontrol form-control' %>
  </div>

  <!-- it list all types of food avalibale in the application -->
  <div class="field">
    <%= f.label :type_id, class: 'form-group' %>
    <%= f.collection_select :type_id, Type.all, :id, :name, class: 'appformcontrol form-control' %> 
  </div>

    <!-- it lists all timing avalibale in the application -->
  <div>
    <%= f.label :time, class: 'form-group' %>
    <%= render partial: 'times_check', class: 'appformcontrol form-control' %>
  </div>

   <!-- it lists all resturants avalibale in the application -->
    <div>
    <%= f.label :restaurants, class: 'form-group' %>
    <%= render partial: 'restaurants_check', class: 'appformcontrol form-control' %>
  </div>

  <div class="field">
    <%= f.label :servingSize,  class: 'form-group' %>
    <%= f.number_field :servingSize , class: 'appformcontrol form-control'%>
  </div>
  <div class="field">
    <%= f.label :calories,  class: 'form-group' %><br>
    <%= f.number_field :calories, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :protein,  class: 'form-group' %>
    <%= f.text_field :protein, class: 'appformcontrol form-control'%>
  </div>
  <div class="field">
    <%= f.label :totalFat,  class: 'form-group' %>
    <%= f.text_field :totalFat, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :saturated,  class: 'form-group' %>
    <%= f.text_field :saturated, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :trans,  class: 'form-group' %>
    <%= f.text_field :trans, class: 'appformcontrol form-control'%>
  </div>
  <div class="field">
    <%= f.label :cholesterol,  class: 'form-group' %>
    <%= f.text_field :cholesterol, class: 'appformcontrol form-control'%>
  </div>
  <div class="field">
    <%= f.label :carbohydrates,  class: 'form-group' %>
    <%= f.text_field :carbohydrates, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :sugars,  class: 'form-group' %>
    <%= f.text_field :sugars, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :dietaryFiber,  class: 'form-group' %>
    <%= f.text_field :dietaryFiber, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :sodium,  class: 'form-group' %>
    <%= f.text_field :sodium, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :potassium,  class: 'form-group' %>
    <%= f.text_field :potassium, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :magnesium,  class: 'form-group' %>
    <%= f.text_field :magnesium, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :calcium,  class: 'form-group' %>
    <%= f.text_field :calcium, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :iron,  class: 'form-group' %>
    <%= f.text_field :iron, class: 'appformcontrol form-control' %>
  </div>
  <div class="field">
    <%= f.label :vitaminD,  class: 'form-group' %>
    <%= f.text_field :vitaminD, class: 'appformcontrol form-control' %>
  </div>

<br>
  <strong><p class="form-group"> Allergies and Diet</p></strong>
  
  <div class="field">
    <%= f.check_box :eggAllergy %> Egg Allergy &nbsp; &nbsp;
    <%= f.label :eggAllergy, class: 'appcheck form-group' do %>
    <%end%>
  </div>
  <div class="field">
    <%= f.check_box :fishAllergy %> Fish Allergy &nbsp; &nbsp;
    <%= f.label :fishAllergy,  class: 'appcheck form-group'  do %>
     <%end%>
  </div>
  <div class="field">
      <%= f.check_box :shellfishAllergy %> Shellfish Allergy &nbsp; &nbsp;
    <%= f.label :shellfishAllergy,  class: 'appcheck form-group' do %>
  <%end%>
  </div>
  <div class="field">
     <%= f.check_box :soyAllergy %> Soy Allergy &nbsp; &nbsp;
    <%= f.label :soyAllergy,  class: 'appcheck form-group' do %>
    <%end%>
  </div>
  <div class="field">
     <%= f.check_box :dairyAllergy %> Dairy Allergy &nbsp; &nbsp;
    <%= f.label :dairyAllergy,  class: 'appcheck form-group' do %>
    <%end%>
   
  </div>
  <div class="field">
       <%= f.check_box :milkAllergy %> Milk Allergy &nbsp; &nbsp;
    <%= f.label :milkAllergy,  class: 'appcheck form-group' do %>
    <%end%>
  </div>
  <div class="field">
    <%= f.check_box :wheatAllergy %> Wheat Allergy &nbsp; &nbsp;
    <%= f.label :wheatAllergy,  class: 'appcheck form-group' do %>
    <%end%>
  </div>
    <div class="field">
       <%= f.check_box :g6pdAllergy %> g6pd Allergy
    <%= f.label :g6pdAllergy,  class: 'appcheck form-group' do%>
   <%end%>
  </div>
      <div class="field">
    <%= f.check_box :vegetarian %> Vegetarian
    <%= f.label :vegetarian, class: 'appcheck form-group' do  %>
    <%end%>
  </div>


      </div>
    <div class="actions">
      <%= f.submit class: 'userformbutton btn btn-info' %>
      <%= link_to 'Back', foods_path, class: 'userformbutton btn btn-info userbackbutton'%>
    </div>

<% end %>

app/views/foods/_restaurants_check.html.erb
<!-- This section list all resturants in the application as check box for the form -->

<p>
  <% for restaurant in Restaurant.all  %>
     <%= check_box_tag "restaurant_ids[]", restaurant.id, @food.restaurants.include?(restaurant) %>
     <%= restaurant.name %>
     <br />
  <% end  %>
</p>

app/views/foods/_restaurants_list.html.erb
<!-- This section list all resturants that this specific food avalibale in -->


<p>
	<ul>
		<% for restaurant in @food.restaurants  %>
			<li><%= restaurant.name %></li>
		<% end  %>
	</ul>
</p>

app/views/foods/_times_check.html.erb
<!-- This section list all times in the application as check box for the form -->


<p>
  <% for meal_time in MealTime.all  %>
     <%= check_box_tag "meal_time_ids[]", meal_time.id, @food.meal_times.include?(meal_time) %>
     <%= meal_time.time %>
     <br />
  <% end  %>
</p>

app/views/foods/_times_list.html.erb
<!-- This section list all times that this specific food avalibale in-->


<p>
	<ul>
		<% for meal_time in @food.meal_times  %>
			<li><%= meal_time.time %></li>
		<% end  %>

	</ul>
</p>

app/views/foods/edit.html.erb
<!-- the edit page -->

<!--Start Edit Foods Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div class="section-title text-center">
          <h3>Edit Food</h3>
        </div>
      </div>
<!--end Edit Food Heading section-->
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <section>
            <div class="shadbox">
              <div class="panel-body text-left">
                <!-- the form is rendered in this page -->
                <%= render 'form' %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/foods/fsearch.html.erb
<!-- the page that comes after searching by name -->

<!-- Start Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="appHeading" class="section-title text-center">
          <h3>The foods you searched for</h3>
          <p>So what will you eat?</p>
        </div>
      </div>
<!--end of heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          
            <div class=" shadbox">
              <table class="table text-center" >

                <!-- list all the food results -->
                <% if @foods.empty? %>
                <p> No records found</p>
                <% else %>
                <% @foods.each do |food| %>
                  <tr>
                  <td><%= link_to food.name, food %></td>
                    </tr>
                    <% end %>
                  <% end %>
                </table>

            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/foods/index.html.erb
<!-- the page that lists all the foods in the application -->


<!-- Start foods Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="appHeading" class="section-title text-center">
          <h3>Listing foods</h3>
          <p>Add, Edit and Delete foods</p>
        </div>
      </div>
<!--end of foods heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div id="listingappPanel" >
            <div class="panel-body shadbox">
              <table class="table text-left" >
                <tr>
                  <th>Food Name</th>
                  <th></th>
                  </tr>
                  <% @foods.each do |food| %> 
                    <tr>
                    <td><%= food.name %></td>
                    <td> 

                      <!-- the buttons used for show, edit and distroy -->
                      <div class="pull-right hidden-phone">
                          <div id="listingfoodsbuttons">
                            <button class="btn btn-default btn-xs">
                              <!--<i class="fa fa-check"></i>-->
                              <%= link_to '', food, :class =>'fa fa-check' %>
                            </button>
                            <button class="btn btn-default btn-xs">
                              <!--<i class="fa fa-pencil"></i>-->
                              <%= link_to '', edit_food_path(food), :class =>'fa fa-pencil' %>
                            </button>
                            <button class="btn btn-default btn-xs">
                              <!--<i class="fa fa-times"></i>-->
                              <%= link_to '', food, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'fa fa-times' %>
                            </button>
                        </div>
                      </div>
                    </td>
                    </tr>
                  <% end %>
                </table>
              <%= link_to 'Add New food', new_food_path, class: 'appformbutton btn btn-info appbackbutton'%>
              <%= link_to 'Back', nutritionist_path, class: 'appformbutton btn btn-info appbackbutton'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<!-- create new food page -->


         <!--Start new Food Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div class="section-title text-center">
          <h3>New Food</h3>
        </div>
      </div>
            <!--end new food heading section            -->
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <section>
            <div class="shadbox">
              <div class="panel-body text-left">

                <!--  it render the form to be used for creating a new food -->
                <%= render 'form' %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/foods/show.html.erb
<!-- This page shows the specific food page -->
<!-- it shoes where the food is available, when it is available, it belongs to what type of food and the food's 
  nutrition fact label -->

<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
  <div class="container">
    <div class="fontshow">


              <div class="col-md-12 col-md-offset-2">  
              <div class="row">
                      
                  <div class="col-md-4">

                    <div class="row">
                        <div class="shadbox">

                          <div class="row">
                            <h1><%= @food.name %></h1>
                          </div>
                          <hr>
                          <div class="row vdivide">

                            <div class="col-md-6">
                              <div class="row">
                                <h5>Type</h5>
                              <p><%= @food.type.name %></p>
                              </div>
                              <hr>
                              <div class="row">
                                <h5>Available During</h5>
                              <p><%= render partial: 'times_list' %>
                              </div>
                            </div>
                            <div class="col-md-6">
                              <h5>Served At</h5>
                              <p><%= render partial: 'restaurants_list'%></p>
                            </div>
                          </div>

                          

                           
                        </div>
                    </div>
                    
                    <div class="row">
                      <div class="shadbox">

                        <h5>Allergens & Diet</h5>

                        <% if @food.eggAllergy==true%>
                        <%= image_tag("egg-free.svg", class: 'im', :alt => "rss feed") %>
                        <h6>Egg Allergy</h6>
                        <% end %>

                        <% if @food.fishAllergy==true%>
                        <%= image_tag("fish.svg", class: 'im', :alt => "rss feed") %>
                        <h6>Fish Allergy</h6>
                        <% end %>

                        <% if @food.shellfishAllergy==true%>
                        <%= image_tag("shell.svg", class: 'im', :alt => "rss feed") %>
                        <h6>Shellfish Allergy</h6>
                        <% end %>


                        <% if @food.soyAllergy==true%>
                        <%= image_tag("soy.svg", class: 'im', :alt => "rss feed") %>
                        <h6>Soy Allergy</h6>
                        <% end %>


                        <% if @food.dairyAllergy==true%>
                        <%= image_tag("dairy.svg", class: 'im', :alt => "rss feed") %>
                        <h6>Dairy Allergy</h6>
                        <% end %>


                        <% if @food.milkAllergy==true%>
                        <%= image_tag("milk.svg", class: 'im', :alt => "rss feed") %>
                        <h6>Milk Allergy</h6>
                        <% end %>


                        <% if @food.wheatAllergy==true%>
                        <%= image_tag("wheat.svg", class: 'im', :alt => "rss feed") %>
                        <h6>Wheat Allergy</h6>
                        <% end %>


                        <% if @food.g6pdAllergy==true%>
                        <%= image_tag("g6pd.svg", class: 'im', :alt => "rss feed") %>
                        <h6>G6PD Allergy</h6>
                        <% end %>

                        <% if @food.vegetarian==true%>
                        <%= image_tag("vig.svg", class: 'im', :alt => "rss feed") %>
                        <h6>Vegetarian</h6>
                        <% end %>
                            
                      </div>
                    </div>
                  
                  </div> 

                  <div class="col-md-8 ">
                        <div class="shadlabelbox" >
                          <section class="performance-facts">
                            </br>
                              <header class="performance-facts__header">
                                <h2 class="performance-facts__title">Nutrition Facts</h2>
                                    <p>Serving Size <%= @food.servingSize %></p>
                              </header>
                            
                              <table class="performance-facts__table">
                                <thead>
                                  <tr>
                                    <th colspan="3" class="small-info">
                                      Amount Per Serving
                                    </th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <th colspan="2">
                                      <b>Calories</b>
                                      <%= @food.calories %>
                                    </th>
                                  </tr>
                                  <tr class="thick-row">
                              <table class="performance-facts__table">
                                <thead>
                                </thead>
                                <tbody>
                                  <tr class="thick-row">
                                    <td colspan="3" class="small-info">
                                      
                                      <b>% Daily Value*</b>
                                    </td>
                                  </tr>
                                  <tr>
                                    <th colspan="2">
                                      <b>Protein</b>
                                      <%= @food.protein %>g
                                    </th>
                                    <td>
                                     <b><%= ((@food.protein/48.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                  <tr>
                                    <th colspan="2">
                                      <b>Total Fat</b>
                                      <%= @food.totalFat %>g
                                    </th>
                                    <td>
                                      <b><%= ((@food.totalFat/65.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                  <tr>
                                    <td class="blank-cell">
                                    </td>
                                    <th>
                                      Saturated Fat
                                      <%= @food.saturated %>g
                                    </th>
                                    <td>
                                      <b><%= ((@food.saturated/20.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                  <tr>
                                    <td class="blank-cell">
                                    </td>
                                    <th>
                                      Trans Fat
                                      <%= @food.trans %>g
                                    </th>
                                    <td>
                                    </td>
                                  </tr>
                                  <tr>
                                    <th colspan="2">
                                      <b>Cholesterol</b>
                                      <%= @food.cholesterol %>mg
                                    </th>
                                    <td>
                                      <b><%= ((@food.cholesterol/300.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                  <tr>
                                    <th colspan="2">
                                      <b>Total Carbohydrate</b>
                                      <%= @food.carbohydrates %>g
                                    </th>
                                    <td>
                                      <b><%= ((@food.carbohydrates/300.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                  <tr>
                                    <td class="blank-cell">
                                    </td>
                                    <th>
                                      Sugars
                                      <%= @food.sugars %>g
                                    </th>
                                    <td>
                                    </td>
                                  </tr>  
                                  <tr>
                                    <th colspan="2">
                                      <b>Dietary Fiber</b>
                                      <%= @food.dietaryFiber %>g
                                    </th>
                                    <td>
                                      <b><%= ((@food.dietaryFiber/25.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                  <tr>
                                    <th colspan="2">
                                      <b>Sodium</b>
                                      <%= @food.sodium %>mg
                                    </th>
                                    <td>
                                      <b><%= ((@food.sodium/2400.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                   <tr>
                                    <th colspan="2">
                                      <b>Potassium</b>
                                      <%= @food.potassium %>mg
                                    </th>
                                    <td>
                                      <b><%= ((@food.potassium/3625.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                   <tr>
                                    <th colspan="2">
                                      <b>Magnesium</b>
                                      <%= @food.magnesium %>mg
                                    </th>
                                    <td>
                                      <b><%= ((@food.magnesium/375.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                   <tr>
                                    <th colspan="2">
                                      <b>Calcium</b>
                                      <%= @food.calcium %>mg
                                    </th>
                                    <td>
                                      <b><%= ((@food.calcium/1024.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                   <tr>
                                    <th colspan="2">
                                      <b>Iron</b>
                                      <%= @food.iron %>mg
                                    </th>
                                    <td>
                                      <b><%= ((@food.iron/17.36)*100).round %>%</b>
                                    </td>
                                  </tr>
                                  <tr >
                                    <th colspan="2">
                                      <b>Vitamin D</b>
                                      <%= @food.vitaminD %>mg
                                    </th>
                                    <td>
                                      <b><%= ((@food.vitaminD/600.0)*100).round %>%</b>
                                    </td>
                                  </tr>
                                </tbody>
                              </table>


                              
                            </section>

                              <% if logged_in? %>
                                <%= link_to 'Back', foods_path, class: 'appformbutton btn btn-info appbackbutton'%>
                                <% else %>
                                <li>
                                  <%= button_to 'Add to My Meal', my_meals_path(food_id: @food), :class => 'mymealbutton' %>
                                </li>
                              <% end %> 
                        </div>
                    </div>
                </div>
          </div>
    </div>
    </div>
    </div>
</div>