config/routes.rb
Rails.application.routes.draw do
  resources :my_meals
  resources :meals
  resources :meal_times

 # get 'nutritionist/index'
  get 'nutritionist' => 'nutritionist#index'

  resources :restaurants
  resources :types
  resources :foods

  resources :searches

# the routes for the log in and log out 
  get 'admin' => 'admin#index' 
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end


  resources :users

# the route to our home page 
  root to: 'visitors#index'

# the route to the shape that will show the result after searching for a food by neame 
  get 'fsearch' => 'foods#fsearch'

# the routes for the steps of configuring a meal 
  get 'configure_a_meal' => 'meal_times#step1'
  get 'configure_a_meal_step1' => 'restaurants#step2'
  get 'configure_a_meal_step2' => 'types#step3'
  get 'configure_a_meal_step3' => 'foods#step4'



end

app/models/meal_time.rb
class MealTime < ActiveRecord::Base

# before saving the time, change it to downcase
	before_save { self.time = time.downcase }

	#Relations
	has_many :food_times
	has_many :foods, through: :food_times

	#Validation
	validates :time, presence: true, uniqueness: true
end

app/controllers/meal_times_controller.rb
class MealTimesController < ApplicationController
  before_action :set_meal_time, only: [:show, :edit, :update, :destroy]

  #do not check if the user is logged_in before preforming step1
  skip_before_action :authenticate, only: [:step1]

  # GET /meal_times
  # GET /meal_times.json
  def index
    @meal_times = MealTime.all
  end

  # GET /meal_times/1
  # GET /meal_times/1.json
  def show
  end

  # GET /meal_times/new
  def new
    @meal_time = MealTime.new
  end

  # GET /meal_times/1/edit
  def edit
  end

  # POST /meal_times
  # POST /meal_times.json
  def create
    @meal_time = MealTime.new(meal_time_params)

    respond_to do |format|
      if @meal_time.save
        format.html { redirect_to @meal_time, notice: 'Meal time was successfully created.' }
        format.json { render :show, status: :created, location: @meal_time }
      else
        format.html { render :new }
        format.json { render json: @meal_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_times/1
  # PATCH/PUT /meal_times/1.json
  def update
    respond_to do |format|
      if @meal_time.update(meal_time_params)
        format.html { redirect_to @meal_time, notice: 'Meal time was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal_time }
      else
        format.html { render :edit }
        format.json { render json: @meal_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_times/1
  # DELETE /meal_times/1.json
  def destroy
    @meal_time.destroy
    respond_to do |format|
      format.html { redirect_to meal_times_url, notice: 'Meal time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # This method take us to a page to be used for Step1 in Configure a Meal process
  # the page will show all the records of meal times from the database 
  def step1
    @meal_times = MealTime.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_time
      @meal_time = MealTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_time_params
      params.require(:meal_time).permit(:time)
    end
end

app/helpers/meal_times_helper.rb
module MealTimesHelper
end

app/views/meal_times/_form.html.erb
<!-- the form that is used to create and edit meal times -->

<%= form_for(@meal_time) do |f| %>
  <% if @meal_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal_time.errors.count, "error") %> prohibited this meal_time from being saved:</h2>

      <ul>
      <% @meal_time.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-left">
    <%= f.label :time, class: 'form-group' %><br>
    <%= f.text_field :time, class: 'appformcontrol form-control' %>
  </div>
  
  <div class="actions">
    <%= f.submit class: ' appformbutton btn btn-info' %>
    <%= link_to 'Back', meal_times_path, class: 'appformbutton btn btn-info appbackbutton'%>
  </div>
<% end %>

app/views/meal_times/edit.html.erb
<!-- the meal times edit page -->

<!--Start Edit Meal Times Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div class="section-title text-center">
          <h3>Edit Meal Time</h3>
        </div>
      </div>
<!--end Edit Meal Time Heading section-->
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <section>
            <div class="shadbox">
              <div class="panel-body">
                <!-- it use the form to edit the meal times -->
                <%= render 'form' %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>
     

app/views/meal_times/index.html.erb
<!-- it is the page that list all the meal times in the system -->
       

<!-- Start meal time Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="appHeading" class="section-title text-center">
          <h3>Listing Meal Timings</h3>
          <p>Add, Edit and Delete Meal Timings</p>
        </div>
      </div>
<!--end of meal time heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div id="listingappPanel">
            <div class="panel-body shadbox">
              <table class="table text-left" >
                <tr>
                  <th>Meal Timings</th>
                </tr>
                <% @meal_times.each do |meal_time| %>
                  <tr>
                                            
                  <td><%= meal_time.time %></td>
                  <td> 
                    <div class="pull-right hidden-phone">
                      <div id="listingappbuttons">
                        <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-check"></i>-->
                          <%= link_to '', meal_time, :class =>'fa fa-check' %>
                        </button>
                        <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-pencil"></i>-->
                          <%= link_to '', edit_meal_time_path(meal_time), :class =>'fa fa-pencil' %>
                        </button>
                        <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-times"></i>-->
                          <%= link_to '', meal_time, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'fa fa-times' %>
                        </button>
                      </div>
                    </div>
                  </td>
                  </tr>
                <% end %>
              </table>
              <%= link_to 'Add New Meal Time', new_meal_time_path, class: 'appformbutton btn btn-info appbackbutton'%>
              <%= link_to 'Back', admin_path, class: 'appformbutton btn btn-info appbackbutton'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
               

app/views/meal_times/new.html.erb
<!-- the create new meal time page -->

<!--Start New Meal Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div class="section-title text-center">
          <h3>New Meal Time</h3>
        </div>
      </div>
<!--end of new meal heading section-->
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <section>
            <div class="shadbox">
              <div class="panel-body">

                <!-- it use the form to add new meal time --> 
                <%= render 'form' %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meal_times/show.html.erb
<!--  the page that will show the specifc time -->

            <!-- Start Show Meal Times Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="ShowappsHeading" class="section-title text-center">
          <h3>Show Meal Time</h3>
        </div>
      </div>
<!--end of show Meal Times heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div id="showappPanel" >
            <div class="panel-body shadbox">
              <table class="table text-left">
                <tr>
                  <th>Meal Time</th>
                </tr>
                <tr>
                  <td><%= @meal_time.time %></td>
                  <td>
                    <button class="btn btn-default btn-xs">
                          <!--<i class="fa fa-pencil"></i>-->
                          <%= link_to '', edit_meal_time_path, :class =>'fa fa-pencil' %>
                      </button>
                    </td>
                </tr>
              </table>
              <div class="row">
              <%= link_to 'Back', meal_times_path, class: 'appformbutton btn btn-info appbackbutton'%>
            </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
              

app/views/meal_times/step1.html.erb
<!--  the first step in configure a meal process, which lists all the meal timings that are in the system -->


<!-- Start users Heading Section -->
<div class='content'>
  <div class='button'></div>
  <div class="mainbody-section text-center">
    <div class="container">
      <div class="row">
        <div id="appHeading" class="section-title text-center">
          <h3>Step 1</h3>
          <p>Choose your desired timing</p>
        </div>
      </div>
<!--end of users heading section-->
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          
            <div class=" shadbox">
              <div class="step1font">
              <table class="table text-center" >
                

                <% @meal_times.each do |meal_time| %>
                  <tr>
                  <td>
                    <%= link_to meal_time.time, configure_a_meal_step1_path(:time => meal_time.time ) %>
                  </td>
                  </tr>

                  <% end %>
                </table>
                </div>

            </div>

            
        </div>
      </div>
    </div>
  </div>
</div>